# Generated by Django 4.0.2 on 2022-02-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Цвет'),
        ),
    ]
