# Generated by Django 3.2.9 on 2022-02-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211213_1525'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
