# Generated by Django 3.2.7 on 2021-10-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientitem',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_ingredients', to='recepies.recipe'),
        ),
    ]
